image:
  repository: ghcr.io/cdelgehier/pihole-exporter
  tag: "0.2.1"
  pullPolicy: IfNotPresent

pihole:
  host: "pihole-web.pihole.svc.cluster.local"
  port: 80
  https: false
  passwordSecretRef:
    name: pihole-password
    key: password

exporter:
  port: 9666
  scrapeInterval: 30
  logLevel: INFO

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 128Mi

serviceMonitor:
  enabled: false
  interval: 30s
  namespace: ""
  labels: {}
